"""Add account_number column on account table

Revision ID: b87d6b6da337
Revises: 479bc53f5bcd
Create Date: 2026-10-05 14:58:55.649189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87d6b6da337'
down_revision: Union[str, Sequence[str], None] = '479bc53f5bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###
